94 tests for assertionsr@devel
pharmaverse/admiraldev pull request #150
Opened 2022-10-28 22:41 UTC by AniaGolab

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-10-28 23:52 UTC, AniaGolab commented
HI @bms63 and @thomas-neitmann, I added 57 tests on **assertions.r** with overall 100% test coverage. I also added a description to the _values_ of the _assert_character_scalar_  and in the _assert_character_scalar_ itself in the **assertions.r**. Please let me know if you want me to add this change into the NEWS function too? Or if you have any other feedback. Thank you :)

2022-10-30 15:07 UTC, bms63 commented
Wow.  You have single-handedly increased the test coverage from 50% to 90%!  A true admiral legend

2022-10-30 15:09 UTC, bms63 commented on tests/testthat/test-assertions.R
> +test_that("Test 12 : `assert_data_frame` doesn't throw an error
```suggestion
test_that("Test 12 : `assert_data_frame` does not throw an error
```

2022-10-30 15:10 UTC, bms63 commented on tests/testthat/test-assertions.R
> +  example_fun <- function(character) {
```suggestion
test_that("Test 16 : `assert_character_scalar` does not throw an error if case_sensitive is FALSE", {
  example_fun <- function(character) {
```

2022-10-30 15:11 UTC, bms63 commented on tests/testthat/test-assertions.R
> +          if values are not NULL and `arg` not in values", {
```suggestion
          if values are not NULL and `arg` is not in values", {
```

2022-10-30 15:12 UTC, bms63 commented on tests/testthat/test-assertions.R
> +test_that("Test 22 : `assert_symbol` doesn't throw an error if optional = TRUE and `arg` = NULL", {
```suggestion
test_that("Test 22 : `assert_symbol` does not throw an error if optional = TRUE and `arg` = NULL", {
```

2022-10-30 15:13 UTC, bms63 reviewed
Can you replace `doesn't` with `does not` please?

2022-10-30 15:16 UTC, bms63 reviewed
Just a few minor grammar issues to address.  Does this give 100% coverage for all the `assertions.R` functions?

2022-10-30 15:33 UTC, bms63 requested changes
Can you remove this from the file and directly call `admiral.test::admiral_dm`

![image](https://user-images.githubusercontent.com/10111024/198887333-4cb31d56-32fc-4ee5-a570-60818c8b47bf.png)

2022-10-31 19:57 UTC, AniaGolab commented
Thank you for the comments Ben! I applied the changes, please let me know if there is anything else to edit :)

2022-11-04 21:54 UTC, bms63 approved these changes
Many thanks for this @AniaGolab.  You single-handedly brought us from 40% to 90% test coverage!!

2022-11-04 21:54 UTC, merged