Closes #156 assert character scalar does not give expected message when case sensitive equals false
pharmaverse/admiraldev pull request #159
Opened 2022-11-07 19:57 UTC by fshanlee

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-11-08 10:30 UTC, bundfussr requested changes

2022-11-08 10:30 UTC, bundfussr commented on R/assertions.R
> +  if (case_sensitive) {
Could you add a comment regarding why `case_adjusted_arg` is used?

2022-11-08 12:17 UTC, bundfussr approved these changes

2022-11-09 12:30 UTC, fshanlee commented
I've made another amendment to assert_character_scalar() and its corresponding testthat scripts: previously, it appeared that the code was attempting to return the function's input in lowercase if `case_sensitive = FALSE`. However, having looked at other functions in assertions.R, I think it would be more consistent to return the input in its original case, regardless of the value of case_sensitive, and indeed the roxygen header for assert_character_scalar() states "_... Otherwise, the input is returned invisibly._" and does not mention changing the case of what is returned depending on case_sensitive. As an aside, I noticed that there are some functions in assertions.R that don't return their input invisibly, even when the roxygen header states that they do--I've opened issue #167 to address this.

2022-11-09 13:01 UTC, bundfussr commented
@fshanlee , please keep the return value as it is, i.e., return lower case if `case_sensitive = FALSE`. We use this to make the argument "case insensitive". If there are conditions on the value in the function code, we use lowercase, e.g.,
```
mode <- assert_character_scalar(mode, case_sensitive = FALSE)
if (mode == "first") {
...
}
```

2022-11-09 16:47 UTC, fshanlee commented
> @fshanlee , please keep the return value as it is, i.e., return lower case if `case_sensitive = FALSE`. We use this to make the argument "case insensitive". If there are conditions on the value in the function code, we use lowercase, e.g.,
> 
> ```
> mode <- assert_character_scalar(mode, case_sensitive = FALSE)
> if (mode == "first") {
> ...
> }
> ```

Hi @bundfussr , I reverted the last commit, so the function will always return lower case when `case_sensitive = FALSE`.

2022-11-14 13:35 UTC, bundfussr commented
@fshanlee , looks good to me.

2022-11-14 15:02 UTC, merged