#3 Copied over the "warning.R" and "test-warning.R" from admiral repo…
pharmaverse/admiraldev pull request #19
Opened 2022-07-21 08:19 UTC by PoojaKumari05

…. No updates done.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/main/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-07-21 22:10 UTC, bms63 commented on R/warnings.R
> +is_valid_dtc <- function(arg) {
#21 Can you update these functions missing roxygen headers please

2022-07-21 22:11 UTC, bms63 commented on R/warnings.R
> +warn_if_incomplete_dtc <- function(dtc, n) {
Update header

2022-07-21 22:12 UTC, bms63 commented on tests/testthat/test-warnings.R
> +library(admiral.test)
Can you update these tests so they follow our unit test guidance for numbering.  
![image](https://user-images.githubusercontent.com/10111024/180323731-9d3cf724-fec0-446b-8c56-e8fbef240cf0.png)

2022-07-21 22:12 UTC, bms63 commented on tests/testthat/test-warnings.R
> +library(admiral.test)
You might be able to use the testthat adding that we created in admiraldev for just this purpose.

2022-07-21 22:13 UTC, bms63 requested changes
Please add roxygen headers and tests numbering

2022-07-22 07:21 UTC, PoojaKumari05 commented
> Please add roxygen headers and tests numbering

Hi @bms63 - Yes, I will update these now. The previous commit was just for copying over the files from admiral-core to admiraldev. I have not updated anything in the code yet but will start updating now. Thanks for the heads-up, noted all the points.  :)

2022-08-23 12:51 UTC, bms63 commented
Hey @PoojaKumari05 we resolved this in another PR so closing now.

2022-08-23 12:51 UTC, closed without merging